version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '${FRONTEND_PORT:-80}:80'
    env_file:
      - .env
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
