CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE IF NOT EXISTS plans (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price_cents INT NOT NULL,
    max_links INT NOT NULL,
    max_clicks_month INT NOT NULL,
    can_export_data BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    plan_id TEXT REFERENCES plans(id),
    clicks_current_month INT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS campaigns (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS links (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id),
    campaign_id TEXT REFERENCES campaigns(id),
    slug TEXT UNIQUE NOT NULL,
    target_url TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS click_events (
    id TEXT, -- UUID generated by app
    link_id TEXT NOT NULL,
    campaign_id TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    ip TEXT,
    country TEXT,
    city TEXT,
    os TEXT,
    browser TEXT,
    device TEXT,
    referer TEXT
);

SELECT create_hypertable('click_events', 'timestamp', if_not_exists => TRUE);

CREATE INDEX IF NOT EXISTS idx_clicks_link_id ON click_events (link_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_clicks_campaign_id ON click_events (campaign_id, timestamp DESC);
