addr: :8080

http:
  read_timeout: 5s
  write_timeout: 10s
  idle_timeout: 120s
  request_timeout: 15s

logger:
  level: info
  app: analytics
  service: redirect
  udp_address:
  enable_caller: false

metrics:
  user: admin
  password: password

geo_ip:
  db_path: database/GeoLite2-City.mmdb
  enabled: true

notifications:
  telegram:
    enabled: true
