package http

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/go-chi/cors"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"github.com/shanth1/gotools/consts"
	"github.com/shanth1/gotools/log"
	_ "github.com/shanth1/gotrace/docs" // docs is generated by Swag CLI, required for Swagger UI
	"github.com/shanth1/gotrace/internal/adapters/handler/http/handlers"
	httpMw "github.com/shanth1/gotrace/internal/adapters/handler/http/middleware"
	v1 "github.com/shanth1/gotrace/internal/adapters/handler/http/v1"
	"github.com/shanth1/gotrace/internal/config"
	"github.com/shanth1/gotrace/internal/core/ports"
	httpSwagger "github.com/swaggo/http-swagger"
)

// TODO: router config struct
func NewRouter(
	cfg *config.Config,
	authService ports.AuthService,
	analyticsService ports.AnalyticsService,
	campaignService ports.CampaignService,
	linkService ports.LinkService,
	redirectService ports.RedirectService,
	userService ports.UserService,
	billingService ports.BillingService,
	linkRepo ports.LinkRepository,
	userRepo ports.UserRepository,
	planRepo ports.PlanRepository,
	logger log.Logger,
) http.Handler {
	r := chi.NewRouter()

	r.Use(middleware.RequestID)
	r.Use(middleware.RealIP)
	r.Use(httpMw.Logger(logger))
	r.Use(middleware.Recoverer)
	r.Use(cors.Handler(cors.Options{
		AllowedOrigins:   []string{"*"}, // TODO: cfg.HTTP.AllowedOrigins
		AllowedMethods:   []string{"GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"},
		AllowedHeaders:   []string{"Accept", "Authorization", "Content-Type", "X-CSRF-Token"},
		ExposedHeaders:   []string{"Link"},
		AllowCredentials: true,
		MaxAge:           300,
	}))
	r.Use(httpMw.Metrics)
	r.Use(middleware.Timeout(cfg.HTTP.RequestTimeout))

	redirectHandler := handlers.NewRedirectHandler(redirectService)

	// Handlers
	authHandlerV1 := v1.NewAuthHandler(authService)
	adminHandlerV1 := v1.NewAdminHandler(userService)
	userHandlerV1 := v1.NewUserHandler(userService)
	campaignHandlerV1 := v1.NewCampaignHandler(campaignService)
	linkHandlerV1 := v1.NewLinkHandler(linkService, campaignService)
	analyticsHandlerV1 := v1.NewAnalyticsHandler(analyticsService)
	billingHandlerV1 := v1.NewBillingHandler(billingService)

	// Middleware
	quotaMiddleware := httpMw.NewQuotaMiddleware(linkRepo, userRepo, planRepo)
	jwtAuthMiddleware := httpMw.JWTAuth(cfg)
	apiKeyAuthMiddleware := httpMw.APIKeyAuth(cfg)

	// --- Public Routes ---
	r.Get("/health", handlers.HealthCheck)
	r.With(quotaMiddleware.CheckClickLimit).Get("/{slug}", redirectHandler.Redirect)
	r.Group(func(sys chi.Router) {
		if cfg.Metrics.User != "" && cfg.Metrics.Password != "" {
			sys.Use(httpMw.BasicAuth(cfg.Metrics.User, cfg.Metrics.Password))
		}
		sys.Handle("/metrics", promhttp.Handler())
	})
	if cfg.Env != consts.EnvProd {
		logger.Info().Msg("Swagger UI enabled at /swagger/index.html")
		r.Get("/swagger/*", httpSwagger.Handler(
			httpSwagger.URL("/swagger/doc.json"),
		))
	}

	// --- API v1 Group ---
	r.Route("/api/v1", func(r chi.Router) {

		// --- Auth Routes  ---
		r.Route("/auth", func(r chi.Router) {
			r.With(apiKeyAuthMiddleware).Post("/register", authHandlerV1.Register)
			r.Post("/login", authHandlerV1.Login)

			// TODO:
			// r.Post("/refresh", authHandlerV1.RefreshToken)
		})

		r.Route("/users", func(r chi.Router) {
			r.Get("/tree", userHandlerV1.GetProfileTree)

			// TODO:
			// r.Get("/me", handlers.User.GetMe)
			// r.Patch("/me", handlers.User.UpdateMe)
		})

		// --- Service Routes  ---
		r.Route("/billing", func(r chi.Router) {
			r.Get("/plans", billingHandlerV1.GetPlans)

			// TODO: currencies, payment systems, etc.
		})

		// --- Client Routes (Protected) ---
		r.Group(func(r chi.Router) {
			r.Use(jwtAuthMiddleware)

			r.Route("/campaigns", func(r chi.Router) {
				r.Get("/", campaignHandlerV1.GetCampaigns)
				r.Post("/", campaignHandlerV1.CreateCampaign)
			})

			r.Route("/links", func(r chi.Router) {
				r.Post("/", linkHandlerV1.CreateLink)
				r.Get("/", linkHandlerV1.GetLinks)
				r.Delete("/{id}", linkHandlerV1.DeleteLink)

				// TODO:
				// r.Route("/{id}", func(r chi.Router) {
				// 	r.Get("/", linkHandlerV1.GetLink)
				// 	r.Delete("/", linkHandlerV1.DeleteLink)
				// 	r.Patch("/", linkHandlerV1.UpdateLink)
				// })
			})

			// Analytics (Visx Ready)
			r.Route("/analytics", func(r chi.Router) {
				r.Get("/summary", analyticsHandlerV1.GetSummary)
				r.Get("/stream", analyticsHandlerV1.GetStreamGraph)
				r.Get("/flow", analyticsHandlerV1.GetSankeyFlow)
				r.Get("/geo", analyticsHandlerV1.GetGeoMap)
				r.Get("/quality", analyticsHandlerV1.GetQualityRadar)
				r.Get("/heatmap", analyticsHandlerV1.GetHeatmap) // Heatmap
				r.Get("/stats", analyticsHandlerV1.GetStats)     // BarGroup, Pies
			})
		})

		// --- Admin Routes (Protected + Admin Role) ---
		r.Group(func(r chi.Router) {
			r.Use(jwtAuthMiddleware, httpMw.AdminOnly)

			r.Route("/admin", func(r chi.Router) {
				r.Route("/users", func(r chi.Router) {
					r.Get("/", adminHandlerV1.GetUsers)
					r.Patch("/{id}/status", adminHandlerV1.UpdateUserStatus)
					r.Patch("/{id}/plan", adminHandlerV1.UpdateUserPlan)
				})

				// TODO: plan CRUD
				// r.Get("/plans", handlers.adminHandlerV1.GetAllPlansIncludingHidden)
			})
		})
	})

	return r
}
