// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=mocks/repositories_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/shanth1/gotrace/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockUserRepository) FindAll(ctx context.Context, limit, offset int) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUserRepositoryMockRecorder) FindAll(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUserRepository)(nil).FindAll), ctx, limit, offset)
}

// FindByEmail mocks base method.
func (m *MockUserRepository) FindByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(ctx context.Context, id domain.UserID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), ctx, id)
}

// IncrementUsage mocks base method.
func (m *MockUserRepository) IncrementUsage(ctx context.Context, userID domain.UserID, delta int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUsage", ctx, userID, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementUsage indicates an expected call of IncrementUsage.
func (mr *MockUserRepositoryMockRecorder) IncrementUsage(ctx, userID, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUsage", reflect.TypeOf((*MockUserRepository)(nil).IncrementUsage), ctx, userID, delta)
}

// ResetUsage mocks base method.
func (m *MockUserRepository) ResetUsage(ctx context.Context, userID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetUsage", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetUsage indicates an expected call of ResetUsage.
func (mr *MockUserRepositoryMockRecorder) ResetUsage(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetUsage", reflect.TypeOf((*MockUserRepository)(nil).ResetUsage), ctx, userID)
}

// Save mocks base method.
func (m *MockUserRepository) Save(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserRepositoryMockRecorder) Save(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserRepository)(nil).Save), ctx, user)
}

// MockCampaignRepository is a mock of CampaignRepository interface.
type MockCampaignRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignRepositoryMockRecorder
	isgomock struct{}
}

// MockCampaignRepositoryMockRecorder is the mock recorder for MockCampaignRepository.
type MockCampaignRepositoryMockRecorder struct {
	mock *MockCampaignRepository
}

// NewMockCampaignRepository creates a new mock instance.
func NewMockCampaignRepository(ctrl *gomock.Controller) *MockCampaignRepository {
	mock := &MockCampaignRepository{ctrl: ctrl}
	mock.recorder = &MockCampaignRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaignRepository) EXPECT() *MockCampaignRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCampaignRepository) Delete(ctx context.Context, userID domain.UserID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCampaignRepositoryMockRecorder) Delete(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCampaignRepository)(nil).Delete), ctx, userID, id)
}

// FindAllByUserID mocks base method.
func (m *MockCampaignRepository) FindAllByUserID(ctx context.Context, userID domain.UserID) ([]*domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByUserID indicates an expected call of FindAllByUserID.
func (mr *MockCampaignRepositoryMockRecorder) FindAllByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserID", reflect.TypeOf((*MockCampaignRepository)(nil).FindAllByUserID), ctx, userID)
}

// FindByID mocks base method.
func (m *MockCampaignRepository) FindByID(ctx context.Context, id string) (*domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCampaignRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCampaignRepository)(nil).FindByID), ctx, id)
}

// Save mocks base method.
func (m *MockCampaignRepository) Save(ctx context.Context, campaign *domain.Campaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, campaign)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCampaignRepositoryMockRecorder) Save(ctx, campaign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCampaignRepository)(nil).Save), ctx, campaign)
}

// MockPlanRepository is a mock of PlanRepository interface.
type MockPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlanRepositoryMockRecorder
	isgomock struct{}
}

// MockPlanRepositoryMockRecorder is the mock recorder for MockPlanRepository.
type MockPlanRepositoryMockRecorder struct {
	mock *MockPlanRepository
}

// NewMockPlanRepository creates a new mock instance.
func NewMockPlanRepository(ctrl *gomock.Controller) *MockPlanRepository {
	mock := &MockPlanRepository{ctrl: ctrl}
	mock.recorder = &MockPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanRepository) EXPECT() *MockPlanRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockPlanRepository) FindAll(ctx context.Context) ([]*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPlanRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPlanRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockPlanRepository) FindByID(ctx context.Context, id string) (*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPlanRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPlanRepository)(nil).FindByID), ctx, id)
}

// FindDefault mocks base method.
func (m *MockPlanRepository) FindDefault(ctx context.Context) (*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDefault", ctx)
	ret0, _ := ret[0].(*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDefault indicates an expected call of FindDefault.
func (mr *MockPlanRepositoryMockRecorder) FindDefault(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDefault", reflect.TypeOf((*MockPlanRepository)(nil).FindDefault), ctx)
}

// Save mocks base method.
func (m *MockPlanRepository) Save(ctx context.Context, plan *domain.Plan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPlanRepositoryMockRecorder) Save(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPlanRepository)(nil).Save), ctx, plan)
}

// MockLinkRepository is a mock of LinkRepository interface.
type MockLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockLinkRepositoryMockRecorder is the mock recorder for MockLinkRepository.
type MockLinkRepositoryMockRecorder struct {
	mock *MockLinkRepository
}

// NewMockLinkRepository creates a new mock instance.
func NewMockLinkRepository(ctrl *gomock.Controller) *MockLinkRepository {
	mock := &MockLinkRepository{ctrl: ctrl}
	mock.recorder = &MockLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepository) EXPECT() *MockLinkRepositoryMockRecorder {
	return m.recorder
}

// CountByUserID mocks base method.
func (m *MockLinkRepository) CountByUserID(ctx context.Context, userID domain.UserID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockLinkRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockLinkRepository)(nil).CountByUserID), ctx, userID)
}

// Delete mocks base method.
func (m *MockLinkRepository) Delete(ctx context.Context, userID domain.UserID, id domain.LinkID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLinkRepositoryMockRecorder) Delete(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLinkRepository)(nil).Delete), ctx, userID, id)
}

// FindAll mocks base method.
func (m *MockLinkRepository) FindAll(ctx context.Context, filter domain.LinkFilter) ([]*domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filter)
	ret0, _ := ret[0].([]*domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockLinkRepositoryMockRecorder) FindAll(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockLinkRepository)(nil).FindAll), ctx, filter)
}

// FindByID mocks base method.
func (m *MockLinkRepository) FindByID(ctx context.Context, id domain.LinkID) (*domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockLinkRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockLinkRepository)(nil).FindByID), ctx, id)
}

// FindBySlug mocks base method.
func (m *MockLinkRepository) FindBySlug(ctx context.Context, slug string) (*domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", ctx, slug)
	ret0, _ := ret[0].(*domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockLinkRepositoryMockRecorder) FindBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockLinkRepository)(nil).FindBySlug), ctx, slug)
}

// Save mocks base method.
func (m *MockLinkRepository) Save(ctx context.Context, link *domain.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLinkRepositoryMockRecorder) Save(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLinkRepository)(nil).Save), ctx, link)
}

// MockGeoProvider is a mock of GeoProvider interface.
type MockGeoProvider struct {
	ctrl     *gomock.Controller
	recorder *MockGeoProviderMockRecorder
	isgomock struct{}
}

// MockGeoProviderMockRecorder is the mock recorder for MockGeoProvider.
type MockGeoProviderMockRecorder struct {
	mock *MockGeoProvider
}

// NewMockGeoProvider creates a new mock instance.
func NewMockGeoProvider(ctrl *gomock.Controller) *MockGeoProvider {
	mock := &MockGeoProvider{ctrl: ctrl}
	mock.recorder = &MockGeoProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoProvider) EXPECT() *MockGeoProviderMockRecorder {
	return m.recorder
}

// Lookup mocks base method.
func (m *MockGeoProvider) Lookup(ctx context.Context, ip string) (*domain.GeoLocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", ctx, ip)
	ret0, _ := ret[0].(*domain.GeoLocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup.
func (mr *MockGeoProviderMockRecorder) Lookup(ctx, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockGeoProvider)(nil).Lookup), ctx, ip)
}

// MockEventIngestor is a mock of EventIngestor interface.
type MockEventIngestor struct {
	ctrl     *gomock.Controller
	recorder *MockEventIngestorMockRecorder
	isgomock struct{}
}

// MockEventIngestorMockRecorder is the mock recorder for MockEventIngestor.
type MockEventIngestorMockRecorder struct {
	mock *MockEventIngestor
}

// NewMockEventIngestor creates a new mock instance.
func NewMockEventIngestor(ctrl *gomock.Controller) *MockEventIngestor {
	mock := &MockEventIngestor{ctrl: ctrl}
	mock.recorder = &MockEventIngestorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventIngestor) EXPECT() *MockEventIngestorMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEventIngestor) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEventIngestorMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEventIngestor)(nil).Close))
}

// TrackClick mocks base method.
func (m *MockEventIngestor) TrackClick(ctx context.Context, event *domain.ClickEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackClick", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackClick indicates an expected call of TrackClick.
func (mr *MockEventIngestorMockRecorder) TrackClick(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackClick", reflect.TypeOf((*MockEventIngestor)(nil).TrackClick), ctx, event)
}

// MockAnalyticsRepository is a mock of AnalyticsRepository interface.
type MockAnalyticsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsRepositoryMockRecorder
	isgomock struct{}
}

// MockAnalyticsRepositoryMockRecorder is the mock recorder for MockAnalyticsRepository.
type MockAnalyticsRepositoryMockRecorder struct {
	mock *MockAnalyticsRepository
}

// NewMockAnalyticsRepository creates a new mock instance.
func NewMockAnalyticsRepository(ctrl *gomock.Controller) *MockAnalyticsRepository {
	mock := &MockAnalyticsRepository{ctrl: ctrl}
	mock.recorder = &MockAnalyticsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsRepository) EXPECT() *MockAnalyticsRepositoryMockRecorder {
	return m.recorder
}

// CountTotal mocks base method.
func (m *MockAnalyticsRepository) CountTotal(ctx context.Context, filter domain.AnalyticsFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotal", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotal indicates an expected call of CountTotal.
func (mr *MockAnalyticsRepositoryMockRecorder) CountTotal(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotal", reflect.TypeOf((*MockAnalyticsRepository)(nil).CountTotal), ctx, filter)
}

// GetFlowData mocks base method.
func (m *MockAnalyticsRepository) GetFlowData(ctx context.Context, filter domain.AnalyticsFilter, stages []string) (*domain.SankeyData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlowData", ctx, filter, stages)
	ret0, _ := ret[0].(*domain.SankeyData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlowData indicates an expected call of GetFlowData.
func (mr *MockAnalyticsRepositoryMockRecorder) GetFlowData(ctx, filter, stages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlowData", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetFlowData), ctx, filter, stages)
}

// GetHeatmapData mocks base method.
func (m *MockAnalyticsRepository) GetHeatmapData(ctx context.Context, filter domain.AnalyticsFilter) ([]domain.HeatmapPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeatmapData", ctx, filter)
	ret0, _ := ret[0].([]domain.HeatmapPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeatmapData indicates an expected call of GetHeatmapData.
func (mr *MockAnalyticsRepositoryMockRecorder) GetHeatmapData(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeatmapData", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetHeatmapData), ctx, filter)
}

// GetTimeSeriesGrouped mocks base method.
func (m *MockAnalyticsRepository) GetTimeSeriesGrouped(ctx context.Context, filter domain.AnalyticsFilter, dimension string, interval time.Duration) ([]domain.StackedPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeSeriesGrouped", ctx, filter, dimension, interval)
	ret0, _ := ret[0].([]domain.StackedPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeSeriesGrouped indicates an expected call of GetTimeSeriesGrouped.
func (mr *MockAnalyticsRepositoryMockRecorder) GetTimeSeriesGrouped(ctx, filter, dimension, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeSeriesGrouped", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetTimeSeriesGrouped), ctx, filter, dimension, interval)
}

// GetTopStats mocks base method.
func (m *MockAnalyticsRepository) GetTopStats(ctx context.Context, filter domain.AnalyticsFilter, dimension string, limit int) ([]domain.CategoryStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopStats", ctx, filter, dimension, limit)
	ret0, _ := ret[0].([]domain.CategoryStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopStats indicates an expected call of GetTopStats.
func (mr *MockAnalyticsRepositoryMockRecorder) GetTopStats(ctx, filter, dimension, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopStats", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetTopStats), ctx, filter, dimension, limit)
}

// SaveBatch mocks base method.
func (m *MockAnalyticsRepository) SaveBatch(ctx context.Context, events []*domain.ClickEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockAnalyticsRepositoryMockRecorder) SaveBatch(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockAnalyticsRepository)(nil).SaveBatch), ctx, events)
}
