// Code generated by MockGen. DO NOT EDIT.
// Source: repositories.go
//
// Generated by this command:
//
//	mockgen -source=repositories.go -destination=mocks/repositories_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/shanth1/gotrace/internal/core/domain"
	ports "github.com/shanth1/gotrace/internal/core/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockUserRepository) FindAll(ctx context.Context, limit, offset int) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, limit, offset)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUserRepositoryMockRecorder) FindAll(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUserRepository)(nil).FindAll), ctx, limit, offset)
}

// FindByEmail mocks base method.
func (m *MockUserRepository) FindByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockUserRepositoryMockRecorder) FindByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindByEmail), ctx, email)
}

// FindByID mocks base method.
func (m *MockUserRepository) FindByID(ctx context.Context, id domain.UserID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockUserRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockUserRepository)(nil).FindByID), ctx, id)
}

// IncrementClickCount mocks base method.
func (m *MockUserRepository) IncrementClickCount(ctx context.Context, userID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementClickCount", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementClickCount indicates an expected call of IncrementClickCount.
func (mr *MockUserRepositoryMockRecorder) IncrementClickCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementClickCount", reflect.TypeOf((*MockUserRepository)(nil).IncrementClickCount), ctx, userID)
}

// Save mocks base method.
func (m *MockUserRepository) Save(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserRepositoryMockRecorder) Save(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserRepository)(nil).Save), ctx, user)
}

// MockCampaignRepository is a mock of CampaignRepository interface.
type MockCampaignRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignRepositoryMockRecorder
	isgomock struct{}
}

// MockCampaignRepositoryMockRecorder is the mock recorder for MockCampaignRepository.
type MockCampaignRepositoryMockRecorder struct {
	mock *MockCampaignRepository
}

// NewMockCampaignRepository creates a new mock instance.
func NewMockCampaignRepository(ctrl *gomock.Controller) *MockCampaignRepository {
	mock := &MockCampaignRepository{ctrl: ctrl}
	mock.recorder = &MockCampaignRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaignRepository) EXPECT() *MockCampaignRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCampaignRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCampaignRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCampaignRepository)(nil).Delete), ctx, id)
}

// FindAllByUserID mocks base method.
func (m *MockCampaignRepository) FindAllByUserID(ctx context.Context, userID domain.UserID) ([]*domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUserID", ctx, userID)
	ret0, _ := ret[0].([]*domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByUserID indicates an expected call of FindAllByUserID.
func (mr *MockCampaignRepositoryMockRecorder) FindAllByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserID", reflect.TypeOf((*MockCampaignRepository)(nil).FindAllByUserID), ctx, userID)
}

// FindByID mocks base method.
func (m *MockCampaignRepository) FindByID(ctx context.Context, id string) (*domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCampaignRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCampaignRepository)(nil).FindByID), ctx, id)
}

// Save mocks base method.
func (m *MockCampaignRepository) Save(ctx context.Context, campaign *domain.Campaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, campaign)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCampaignRepositoryMockRecorder) Save(ctx, campaign any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCampaignRepository)(nil).Save), ctx, campaign)
}

// MockPlanRepository is a mock of PlanRepository interface.
type MockPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPlanRepositoryMockRecorder
	isgomock struct{}
}

// MockPlanRepositoryMockRecorder is the mock recorder for MockPlanRepository.
type MockPlanRepositoryMockRecorder struct {
	mock *MockPlanRepository
}

// NewMockPlanRepository creates a new mock instance.
func NewMockPlanRepository(ctrl *gomock.Controller) *MockPlanRepository {
	mock := &MockPlanRepository{ctrl: ctrl}
	mock.recorder = &MockPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanRepository) EXPECT() *MockPlanRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockPlanRepository) FindAll(ctx context.Context) ([]*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockPlanRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockPlanRepository)(nil).FindAll), ctx)
}

// FindByID mocks base method.
func (m *MockPlanRepository) FindByID(ctx context.Context, id string) (*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPlanRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPlanRepository)(nil).FindByID), ctx, id)
}

// FindDefault mocks base method.
func (m *MockPlanRepository) FindDefault(ctx context.Context) (*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDefault", ctx)
	ret0, _ := ret[0].(*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDefault indicates an expected call of FindDefault.
func (mr *MockPlanRepositoryMockRecorder) FindDefault(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDefault", reflect.TypeOf((*MockPlanRepository)(nil).FindDefault), ctx)
}

// Save mocks base method.
func (m *MockPlanRepository) Save(ctx context.Context, plan *domain.Plan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPlanRepositoryMockRecorder) Save(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPlanRepository)(nil).Save), ctx, plan)
}

// MockLinkRepository is a mock of LinkRepository interface.
type MockLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockLinkRepositoryMockRecorder is the mock recorder for MockLinkRepository.
type MockLinkRepositoryMockRecorder struct {
	mock *MockLinkRepository
}

// NewMockLinkRepository creates a new mock instance.
func NewMockLinkRepository(ctrl *gomock.Controller) *MockLinkRepository {
	mock := &MockLinkRepository{ctrl: ctrl}
	mock.recorder = &MockLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepository) EXPECT() *MockLinkRepositoryMockRecorder {
	return m.recorder
}

// CountByUserID mocks base method.
func (m *MockLinkRepository) CountByUserID(ctx context.Context, userID domain.UserID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockLinkRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockLinkRepository)(nil).CountByUserID), ctx, userID)
}

// FindAll mocks base method.
func (m *MockLinkRepository) FindAll(ctx context.Context) ([]*domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockLinkRepositoryMockRecorder) FindAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockLinkRepository)(nil).FindAll), ctx)
}

// FindAllByCampaignID mocks base method.
func (m *MockLinkRepository) FindAllByCampaignID(ctx context.Context, campaignID string) ([]*domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByCampaignID", ctx, campaignID)
	ret0, _ := ret[0].([]*domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByCampaignID indicates an expected call of FindAllByCampaignID.
func (mr *MockLinkRepositoryMockRecorder) FindAllByCampaignID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByCampaignID", reflect.TypeOf((*MockLinkRepository)(nil).FindAllByCampaignID), ctx, campaignID)
}

// FindBySlug mocks base method.
func (m *MockLinkRepository) FindBySlug(ctx context.Context, slug string) (*domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySlug", ctx, slug)
	ret0, _ := ret[0].(*domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySlug indicates an expected call of FindBySlug.
func (mr *MockLinkRepositoryMockRecorder) FindBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySlug", reflect.TypeOf((*MockLinkRepository)(nil).FindBySlug), ctx, slug)
}

// Save mocks base method.
func (m *MockLinkRepository) Save(ctx context.Context, link *domain.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockLinkRepositoryMockRecorder) Save(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockLinkRepository)(nil).Save), ctx, link)
}

// MockClickRepository is a mock of ClickRepository interface.
type MockClickRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClickRepositoryMockRecorder
	isgomock struct{}
}

// MockClickRepositoryMockRecorder is the mock recorder for MockClickRepository.
type MockClickRepositoryMockRecorder struct {
	mock *MockClickRepository
}

// NewMockClickRepository creates a new mock instance.
func NewMockClickRepository(ctrl *gomock.Controller) *MockClickRepository {
	mock := &MockClickRepository{ctrl: ctrl}
	mock.recorder = &MockClickRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickRepository) EXPECT() *MockClickRepositoryMockRecorder {
	return m.recorder
}

// CountTotal mocks base method.
func (m *MockClickRepository) CountTotal(ctx context.Context, filter ports.AnalyticsFilter) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTotal", ctx, filter)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTotal indicates an expected call of CountTotal.
func (mr *MockClickRepositoryMockRecorder) CountTotal(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTotal", reflect.TypeOf((*MockClickRepository)(nil).CountTotal), ctx, filter)
}

// GetFlowData mocks base method.
func (m *MockClickRepository) GetFlowData(ctx context.Context, filter ports.AnalyticsFilter, stages []string) (*domain.SankeyData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFlowData", ctx, filter, stages)
	ret0, _ := ret[0].(*domain.SankeyData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFlowData indicates an expected call of GetFlowData.
func (mr *MockClickRepositoryMockRecorder) GetFlowData(ctx, filter, stages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFlowData", reflect.TypeOf((*MockClickRepository)(nil).GetFlowData), ctx, filter, stages)
}

// GetHeatmapData mocks base method.
func (m *MockClickRepository) GetHeatmapData(ctx context.Context, filter ports.AnalyticsFilter) ([]domain.HeatmapPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeatmapData", ctx, filter)
	ret0, _ := ret[0].([]domain.HeatmapPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeatmapData indicates an expected call of GetHeatmapData.
func (mr *MockClickRepositoryMockRecorder) GetHeatmapData(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeatmapData", reflect.TypeOf((*MockClickRepository)(nil).GetHeatmapData), ctx, filter)
}

// GetTimeSeriesGrouped mocks base method.
func (m *MockClickRepository) GetTimeSeriesGrouped(ctx context.Context, filter ports.AnalyticsFilter, dimension string, interval time.Duration) ([]domain.StackedPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeSeriesGrouped", ctx, filter, dimension, interval)
	ret0, _ := ret[0].([]domain.StackedPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeSeriesGrouped indicates an expected call of GetTimeSeriesGrouped.
func (mr *MockClickRepositoryMockRecorder) GetTimeSeriesGrouped(ctx, filter, dimension, interval any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeSeriesGrouped", reflect.TypeOf((*MockClickRepository)(nil).GetTimeSeriesGrouped), ctx, filter, dimension, interval)
}

// GetTopStats mocks base method.
func (m *MockClickRepository) GetTopStats(ctx context.Context, filter ports.AnalyticsFilter, dimension string, limit int) ([]domain.CategoryStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopStats", ctx, filter, dimension, limit)
	ret0, _ := ret[0].([]domain.CategoryStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopStats indicates an expected call of GetTopStats.
func (mr *MockClickRepositoryMockRecorder) GetTopStats(ctx, filter, dimension, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopStats", reflect.TypeOf((*MockClickRepository)(nil).GetTopStats), ctx, filter, dimension, limit)
}

// Save mocks base method.
func (m *MockClickRepository) Save(ctx context.Context, click *domain.ClickEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, click)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockClickRepositoryMockRecorder) Save(ctx, click any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockClickRepository)(nil).Save), ctx, click)
}

// MockGeoIPRepository is a mock of GeoIPRepository interface.
type MockGeoIPRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGeoIPRepositoryMockRecorder
	isgomock struct{}
}

// MockGeoIPRepositoryMockRecorder is the mock recorder for MockGeoIPRepository.
type MockGeoIPRepositoryMockRecorder struct {
	mock *MockGeoIPRepository
}

// NewMockGeoIPRepository creates a new mock instance.
func NewMockGeoIPRepository(ctrl *gomock.Controller) *MockGeoIPRepository {
	mock := &MockGeoIPRepository{ctrl: ctrl}
	mock.recorder = &MockGeoIPRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeoIPRepository) EXPECT() *MockGeoIPRepositoryMockRecorder {
	return m.recorder
}

// GetInfo mocks base method.
func (m *MockGeoIPRepository) GetInfo(ctx context.Context, ipStr string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInfo", ctx, ipStr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetInfo indicates an expected call of GetInfo.
func (mr *MockGeoIPRepositoryMockRecorder) GetInfo(ctx, ipStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInfo", reflect.TypeOf((*MockGeoIPRepository)(nil).GetInfo), ctx, ipStr)
}
