// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/shanth1/gotrace/internal/core/domain"
	ports "github.com/shanth1/gotrace/internal/core/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx context.Context, email, password string) (string, *domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*domain.User)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, email, password)
}

// Register mocks base method.
func (m *MockAuthService) Register(ctx context.Context, email, password string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, email, password)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceMockRecorder) Register(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthService)(nil).Register), ctx, email, password)
}

// MockAnalyticsService is a mock of AnalyticsService interface.
type MockAnalyticsService struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsServiceMockRecorder
	isgomock struct{}
}

// MockAnalyticsServiceMockRecorder is the mock recorder for MockAnalyticsService.
type MockAnalyticsServiceMockRecorder struct {
	mock *MockAnalyticsService
}

// NewMockAnalyticsService creates a new mock instance.
func NewMockAnalyticsService(ctrl *gomock.Controller) *MockAnalyticsService {
	mock := &MockAnalyticsService{ctrl: ctrl}
	mock.recorder = &MockAnalyticsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsService) EXPECT() *MockAnalyticsServiceMockRecorder {
	return m.recorder
}

// GetCategoryStats mocks base method.
func (m *MockAnalyticsService) GetCategoryStats(ctx context.Context, filter ports.AnalyticsFilter, dimension string) ([]domain.CategoryStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryStats", ctx, filter, dimension)
	ret0, _ := ret[0].([]domain.CategoryStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryStats indicates an expected call of GetCategoryStats.
func (mr *MockAnalyticsServiceMockRecorder) GetCategoryStats(ctx, filter, dimension any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryStats", reflect.TypeOf((*MockAnalyticsService)(nil).GetCategoryStats), ctx, filter, dimension)
}

// GetGeoDistribution mocks base method.
func (m *MockAnalyticsService) GetGeoDistribution(ctx context.Context, filter ports.AnalyticsFilter) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeoDistribution", ctx, filter)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeoDistribution indicates an expected call of GetGeoDistribution.
func (mr *MockAnalyticsServiceMockRecorder) GetGeoDistribution(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeoDistribution", reflect.TypeOf((*MockAnalyticsService)(nil).GetGeoDistribution), ctx, filter)
}

// GetHeatmapData mocks base method.
func (m *MockAnalyticsService) GetHeatmapData(ctx context.Context, filter ports.AnalyticsFilter) ([]domain.HeatmapPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeatmapData", ctx, filter)
	ret0, _ := ret[0].([]domain.HeatmapPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeatmapData indicates an expected call of GetHeatmapData.
func (mr *MockAnalyticsServiceMockRecorder) GetHeatmapData(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeatmapData", reflect.TypeOf((*MockAnalyticsService)(nil).GetHeatmapData), ctx, filter)
}

// GetSankeyData mocks base method.
func (m *MockAnalyticsService) GetSankeyData(ctx context.Context, filter ports.AnalyticsFilter, stages []string) (*domain.SankeyData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSankeyData", ctx, filter, stages)
	ret0, _ := ret[0].(*domain.SankeyData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSankeyData indicates an expected call of GetSankeyData.
func (mr *MockAnalyticsServiceMockRecorder) GetSankeyData(ctx, filter, stages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSankeyData", reflect.TypeOf((*MockAnalyticsService)(nil).GetSankeyData), ctx, filter, stages)
}

// GetStreamGraphData mocks base method.
func (m *MockAnalyticsService) GetStreamGraphData(ctx context.Context, filter ports.AnalyticsFilter, groupBy string) ([]domain.StackedPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamGraphData", ctx, filter, groupBy)
	ret0, _ := ret[0].([]domain.StackedPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamGraphData indicates an expected call of GetStreamGraphData.
func (mr *MockAnalyticsServiceMockRecorder) GetStreamGraphData(ctx, filter, groupBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamGraphData", reflect.TypeOf((*MockAnalyticsService)(nil).GetStreamGraphData), ctx, filter, groupBy)
}

// GetSummary mocks base method.
func (m *MockAnalyticsService) GetSummary(ctx context.Context, filter ports.AnalyticsFilter) (*domain.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, filter)
	ret0, _ := ret[0].(*domain.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockAnalyticsServiceMockRecorder) GetSummary(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockAnalyticsService)(nil).GetSummary), ctx, filter)
}

// GetTrafficQuality mocks base method.
func (m *MockAnalyticsService) GetTrafficQuality(ctx context.Context, filter ports.AnalyticsFilter) (*domain.TrafficQuality, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrafficQuality", ctx, filter)
	ret0, _ := ret[0].(*domain.TrafficQuality)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrafficQuality indicates an expected call of GetTrafficQuality.
func (mr *MockAnalyticsServiceMockRecorder) GetTrafficQuality(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrafficQuality", reflect.TypeOf((*MockAnalyticsService)(nil).GetTrafficQuality), ctx, filter)
}

// MockLinkService is a mock of LinkService interface.
type MockLinkService struct {
	ctrl     *gomock.Controller
	recorder *MockLinkServiceMockRecorder
	isgomock struct{}
}

// MockLinkServiceMockRecorder is the mock recorder for MockLinkService.
type MockLinkServiceMockRecorder struct {
	mock *MockLinkService
}

// NewMockLinkService creates a new mock instance.
func NewMockLinkService(ctrl *gomock.Controller) *MockLinkService {
	mock := &MockLinkService{ctrl: ctrl}
	mock.recorder = &MockLinkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkService) EXPECT() *MockLinkServiceMockRecorder {
	return m.recorder
}

// CreateCampaign mocks base method.
func (m *MockLinkService) CreateCampaign(ctx context.Context, userID, name string) (*domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCampaign", ctx, userID, name)
	ret0, _ := ret[0].(*domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCampaign indicates an expected call of CreateCampaign.
func (mr *MockLinkServiceMockRecorder) CreateCampaign(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCampaign", reflect.TypeOf((*MockLinkService)(nil).CreateCampaign), ctx, userID, name)
}

// CreateLink mocks base method.
func (m *MockLinkService) CreateLink(ctx context.Context, userID, campaignID, targetURL, customSlug string) (*domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", ctx, userID, campaignID, targetURL, customSlug)
	ret0, _ := ret[0].(*domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockLinkServiceMockRecorder) CreateLink(ctx, userID, campaignID, targetURL, customSlug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockLinkService)(nil).CreateLink), ctx, userID, campaignID, targetURL, customSlug)
}

// DeleteLink mocks base method.
func (m *MockLinkService) DeleteLink(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockLinkServiceMockRecorder) DeleteLink(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockLinkService)(nil).DeleteLink), ctx, id)
}

// GetLinks mocks base method.
func (m *MockLinkService) GetLinks(ctx context.Context, campaignID string) ([]*domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", ctx, campaignID)
	ret0, _ := ret[0].([]*domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockLinkServiceMockRecorder) GetLinks(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockLinkService)(nil).GetLinks), ctx, campaignID)
}

// GetUserCampaigns mocks base method.
func (m *MockLinkService) GetUserCampaigns(ctx context.Context, userID string) ([]*domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCampaigns", ctx, userID)
	ret0, _ := ret[0].([]*domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCampaigns indicates an expected call of GetUserCampaigns.
func (mr *MockLinkServiceMockRecorder) GetUserCampaigns(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCampaigns", reflect.TypeOf((*MockLinkService)(nil).GetUserCampaigns), ctx, userID)
}

// GetUserHierarchy mocks base method.
func (m *MockLinkService) GetUserHierarchy(ctx context.Context, userID string) (*domain.HierarchyNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserHierarchy", ctx, userID)
	ret0, _ := ret[0].(*domain.HierarchyNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserHierarchy indicates an expected call of GetUserHierarchy.
func (mr *MockLinkServiceMockRecorder) GetUserHierarchy(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserHierarchy", reflect.TypeOf((*MockLinkService)(nil).GetUserHierarchy), ctx, userID)
}

// MockRedirectService is a mock of RedirectService interface.
type MockRedirectService struct {
	ctrl     *gomock.Controller
	recorder *MockRedirectServiceMockRecorder
	isgomock struct{}
}

// MockRedirectServiceMockRecorder is the mock recorder for MockRedirectService.
type MockRedirectServiceMockRecorder struct {
	mock *MockRedirectService
}

// NewMockRedirectService creates a new mock instance.
func NewMockRedirectService(ctrl *gomock.Controller) *MockRedirectService {
	mock := &MockRedirectService{ctrl: ctrl}
	mock.recorder = &MockRedirectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedirectService) EXPECT() *MockRedirectServiceMockRecorder {
	return m.recorder
}

// ProcessRedirect mocks base method.
func (m *MockRedirectService) ProcessRedirect(ctx context.Context, slug, ip, userAgentString, referer string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRedirect", ctx, slug, ip, userAgentString, referer)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessRedirect indicates an expected call of ProcessRedirect.
func (mr *MockRedirectServiceMockRecorder) ProcessRedirect(ctx, slug, ip, userAgentString, referer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRedirect", reflect.TypeOf((*MockRedirectService)(nil).ProcessRedirect), ctx, slug, ip, userAgentString, referer)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// ChangeUserPlan mocks base method.
func (m *MockUserService) ChangeUserPlan(ctx context.Context, userID, planID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserPlan", ctx, userID, planID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeUserPlan indicates an expected call of ChangeUserPlan.
func (mr *MockUserServiceMockRecorder) ChangeUserPlan(ctx, userID, planID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserPlan", reflect.TypeOf((*MockUserService)(nil).ChangeUserPlan), ctx, userID, planID)
}

// GetAllUsers mocks base method.
func (m *MockUserService) GetAllUsers(ctx context.Context, page, limit int) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx, page, limit)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockUserServiceMockRecorder) GetAllUsers(ctx, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockUserService)(nil).GetAllUsers), ctx, page, limit)
}

// SetUserStatus mocks base method.
func (m *MockUserService) SetUserStatus(ctx context.Context, userID string, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserStatus", ctx, userID, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserStatus indicates an expected call of SetUserStatus.
func (mr *MockUserServiceMockRecorder) SetUserStatus(ctx, userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserStatus", reflect.TypeOf((*MockUserService)(nil).SetUserStatus), ctx, userID, isActive)
}

// MockBillingService is a mock of BillingService interface.
type MockBillingService struct {
	ctrl     *gomock.Controller
	recorder *MockBillingServiceMockRecorder
	isgomock struct{}
}

// MockBillingServiceMockRecorder is the mock recorder for MockBillingService.
type MockBillingServiceMockRecorder struct {
	mock *MockBillingService
}

// NewMockBillingService creates a new mock instance.
func NewMockBillingService(ctrl *gomock.Controller) *MockBillingService {
	mock := &MockBillingService{ctrl: ctrl}
	mock.recorder = &MockBillingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingService) EXPECT() *MockBillingServiceMockRecorder {
	return m.recorder
}

// GetAllPlans mocks base method.
func (m *MockBillingService) GetAllPlans(ctx context.Context) ([]*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPlans", ctx)
	ret0, _ := ret[0].([]*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPlans indicates an expected call of GetAllPlans.
func (mr *MockBillingServiceMockRecorder) GetAllPlans(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPlans", reflect.TypeOf((*MockBillingService)(nil).GetAllPlans), ctx)
}
