// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/shanth1/gotrace/internal/core/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx context.Context, email, password string) (string, *domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*domain.User)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, email, password)
}

// Register mocks base method.
func (m *MockAuthService) Register(ctx context.Context, email, password string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, email, password)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceMockRecorder) Register(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthService)(nil).Register), ctx, email, password)
}

// MockAnalyticsService is a mock of AnalyticsService interface.
type MockAnalyticsService struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsServiceMockRecorder
	isgomock struct{}
}

// MockAnalyticsServiceMockRecorder is the mock recorder for MockAnalyticsService.
type MockAnalyticsServiceMockRecorder struct {
	mock *MockAnalyticsService
}

// NewMockAnalyticsService creates a new mock instance.
func NewMockAnalyticsService(ctrl *gomock.Controller) *MockAnalyticsService {
	mock := &MockAnalyticsService{ctrl: ctrl}
	mock.recorder = &MockAnalyticsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsService) EXPECT() *MockAnalyticsServiceMockRecorder {
	return m.recorder
}

// ExportData mocks base method.
func (m *MockAnalyticsService) ExportData(ctx context.Context, filter domain.AnalyticsFilter) (io.Reader, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportData", ctx, filter)
	ret0, _ := ret[0].(io.Reader)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ExportData indicates an expected call of ExportData.
func (mr *MockAnalyticsServiceMockRecorder) ExportData(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportData", reflect.TypeOf((*MockAnalyticsService)(nil).ExportData), ctx, filter)
}

// GetCategoryStats mocks base method.
func (m *MockAnalyticsService) GetCategoryStats(ctx context.Context, filter domain.AnalyticsFilter, dimension string) ([]domain.CategoryStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryStats", ctx, filter, dimension)
	ret0, _ := ret[0].([]domain.CategoryStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryStats indicates an expected call of GetCategoryStats.
func (mr *MockAnalyticsServiceMockRecorder) GetCategoryStats(ctx, filter, dimension any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryStats", reflect.TypeOf((*MockAnalyticsService)(nil).GetCategoryStats), ctx, filter, dimension)
}

// GetGeoDistribution mocks base method.
func (m *MockAnalyticsService) GetGeoDistribution(ctx context.Context, filter domain.AnalyticsFilter) ([]domain.GeoStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGeoDistribution", ctx, filter)
	ret0, _ := ret[0].([]domain.GeoStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGeoDistribution indicates an expected call of GetGeoDistribution.
func (mr *MockAnalyticsServiceMockRecorder) GetGeoDistribution(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGeoDistribution", reflect.TypeOf((*MockAnalyticsService)(nil).GetGeoDistribution), ctx, filter)
}

// GetHeatmapData mocks base method.
func (m *MockAnalyticsService) GetHeatmapData(ctx context.Context, filter domain.AnalyticsFilter) ([]domain.HeatmapPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeatmapData", ctx, filter)
	ret0, _ := ret[0].([]domain.HeatmapPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeatmapData indicates an expected call of GetHeatmapData.
func (mr *MockAnalyticsServiceMockRecorder) GetHeatmapData(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeatmapData", reflect.TypeOf((*MockAnalyticsService)(nil).GetHeatmapData), ctx, filter)
}

// GetSankeyData mocks base method.
func (m *MockAnalyticsService) GetSankeyData(ctx context.Context, filter domain.AnalyticsFilter, stages []string) (*domain.SankeyData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSankeyData", ctx, filter, stages)
	ret0, _ := ret[0].(*domain.SankeyData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSankeyData indicates an expected call of GetSankeyData.
func (mr *MockAnalyticsServiceMockRecorder) GetSankeyData(ctx, filter, stages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSankeyData", reflect.TypeOf((*MockAnalyticsService)(nil).GetSankeyData), ctx, filter, stages)
}

// GetStreamGraphData mocks base method.
func (m *MockAnalyticsService) GetStreamGraphData(ctx context.Context, filter domain.AnalyticsFilter, groupBy string) ([]domain.StackedPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamGraphData", ctx, filter, groupBy)
	ret0, _ := ret[0].([]domain.StackedPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamGraphData indicates an expected call of GetStreamGraphData.
func (mr *MockAnalyticsServiceMockRecorder) GetStreamGraphData(ctx, filter, groupBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamGraphData", reflect.TypeOf((*MockAnalyticsService)(nil).GetStreamGraphData), ctx, filter, groupBy)
}

// GetSummary mocks base method.
func (m *MockAnalyticsService) GetSummary(ctx context.Context, filter domain.AnalyticsFilter) (*domain.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, filter)
	ret0, _ := ret[0].(*domain.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockAnalyticsServiceMockRecorder) GetSummary(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockAnalyticsService)(nil).GetSummary), ctx, filter)
}

// GetTrafficQuality mocks base method.
func (m *MockAnalyticsService) GetTrafficQuality(ctx context.Context, filter domain.AnalyticsFilter) (*domain.TrafficQuality, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrafficQuality", ctx, filter)
	ret0, _ := ret[0].(*domain.TrafficQuality)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrafficQuality indicates an expected call of GetTrafficQuality.
func (mr *MockAnalyticsServiceMockRecorder) GetTrafficQuality(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrafficQuality", reflect.TypeOf((*MockAnalyticsService)(nil).GetTrafficQuality), ctx, filter)
}

// MockLinkService is a mock of LinkService interface.
type MockLinkService struct {
	ctrl     *gomock.Controller
	recorder *MockLinkServiceMockRecorder
	isgomock struct{}
}

// MockLinkServiceMockRecorder is the mock recorder for MockLinkService.
type MockLinkServiceMockRecorder struct {
	mock *MockLinkService
}

// NewMockLinkService creates a new mock instance.
func NewMockLinkService(ctrl *gomock.Controller) *MockLinkService {
	mock := &MockLinkService{ctrl: ctrl}
	mock.recorder = &MockLinkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkService) EXPECT() *MockLinkServiceMockRecorder {
	return m.recorder
}

// CreateLink mocks base method.
func (m *MockLinkService) CreateLink(ctx context.Context, cmd domain.CreateLinkCmd) (*domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLink", ctx, cmd)
	ret0, _ := ret[0].(*domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLink indicates an expected call of CreateLink.
func (mr *MockLinkServiceMockRecorder) CreateLink(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLink", reflect.TypeOf((*MockLinkService)(nil).CreateLink), ctx, cmd)
}

// DeleteLink mocks base method.
func (m *MockLinkService) DeleteLink(ctx context.Context, userID domain.UserID, id domain.LinkID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockLinkServiceMockRecorder) DeleteLink(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockLinkService)(nil).DeleteLink), ctx, userID, id)
}

// GetLinkList mocks base method.
func (m *MockLinkService) GetLinkList(ctx context.Context, filter domain.LinkFilter) ([]*domain.Link, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkList", ctx, filter)
	ret0, _ := ret[0].([]*domain.Link)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLinkList indicates an expected call of GetLinkList.
func (mr *MockLinkServiceMockRecorder) GetLinkList(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkList", reflect.TypeOf((*MockLinkService)(nil).GetLinkList), ctx, filter)
}

// MockCampaignService is a mock of CampaignService interface.
type MockCampaignService struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignServiceMockRecorder
	isgomock struct{}
}

// MockCampaignServiceMockRecorder is the mock recorder for MockCampaignService.
type MockCampaignServiceMockRecorder struct {
	mock *MockCampaignService
}

// NewMockCampaignService creates a new mock instance.
func NewMockCampaignService(ctrl *gomock.Controller) *MockCampaignService {
	mock := &MockCampaignService{ctrl: ctrl}
	mock.recorder = &MockCampaignServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaignService) EXPECT() *MockCampaignServiceMockRecorder {
	return m.recorder
}

// CreateCampaign mocks base method.
func (m *MockCampaignService) CreateCampaign(ctx context.Context, userID domain.UserID, name string) (*domain.Campaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCampaign", ctx, userID, name)
	ret0, _ := ret[0].(*domain.Campaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCampaign indicates an expected call of CreateCampaign.
func (mr *MockCampaignServiceMockRecorder) CreateCampaign(ctx, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCampaign", reflect.TypeOf((*MockCampaignService)(nil).CreateCampaign), ctx, userID, name)
}

// DeleteCampaign mocks base method.
func (m *MockCampaignService) DeleteCampaign(ctx context.Context, userID domain.UserID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCampaign", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCampaign indicates an expected call of DeleteCampaign.
func (mr *MockCampaignServiceMockRecorder) DeleteCampaign(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCampaign", reflect.TypeOf((*MockCampaignService)(nil).DeleteCampaign), ctx, userID, id)
}

// GetCampaigns mocks base method.
func (m *MockCampaignService) GetCampaigns(ctx context.Context, filter domain.CampaignFilter) ([]*domain.Campaign, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaigns", ctx, filter)
	ret0, _ := ret[0].([]*domain.Campaign)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCampaigns indicates an expected call of GetCampaigns.
func (mr *MockCampaignServiceMockRecorder) GetCampaigns(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaigns", reflect.TypeOf((*MockCampaignService)(nil).GetCampaigns), ctx, filter)
}

// MockRedirectService is a mock of RedirectService interface.
type MockRedirectService struct {
	ctrl     *gomock.Controller
	recorder *MockRedirectServiceMockRecorder
	isgomock struct{}
}

// MockRedirectServiceMockRecorder is the mock recorder for MockRedirectService.
type MockRedirectServiceMockRecorder struct {
	mock *MockRedirectService
}

// NewMockRedirectService creates a new mock instance.
func NewMockRedirectService(ctrl *gomock.Controller) *MockRedirectService {
	mock := &MockRedirectService{ctrl: ctrl}
	mock.recorder = &MockRedirectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedirectService) EXPECT() *MockRedirectServiceMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockRedirectService) Process(ctx context.Context, slug string, meta domain.RequestMetadata) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, slug, meta)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockRedirectServiceMockRecorder) Process(ctx, slug, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockRedirectService)(nil).Process), ctx, slug, meta)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// ChangePlan mocks base method.
func (m *MockUserService) ChangePlan(ctx context.Context, userID domain.UserID, planID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePlan", ctx, userID, planID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePlan indicates an expected call of ChangePlan.
func (mr *MockUserServiceMockRecorder) ChangePlan(ctx, userID, planID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePlan", reflect.TypeOf((*MockUserService)(nil).ChangePlan), ctx, userID, planID)
}

// DeleteUser mocks base method.
func (m *MockUserService) DeleteUser(ctx context.Context, userID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserServiceMockRecorder) DeleteUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUserService)(nil).DeleteUser), ctx, userID)
}

// GetAll mocks base method.
func (m *MockUserService) GetAll(ctx context.Context, page, limit int) ([]*domain.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, page, limit)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAll indicates an expected call of GetAll.
func (mr *MockUserServiceMockRecorder) GetAll(ctx, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockUserService)(nil).GetAll), ctx, page, limit)
}

// GetHierarchy mocks base method.
func (m *MockUserService) GetHierarchy(ctx context.Context, id domain.UserID) (*domain.HierarchyNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHierarchy", ctx, id)
	ret0, _ := ret[0].(*domain.HierarchyNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHierarchy indicates an expected call of GetHierarchy.
func (mr *MockUserServiceMockRecorder) GetHierarchy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHierarchy", reflect.TypeOf((*MockUserService)(nil).GetHierarchy), ctx, id)
}

// SetStatus mocks base method.
func (m *MockUserService) SetStatus(ctx context.Context, userID domain.UserID, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, userID, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockUserServiceMockRecorder) SetStatus(ctx, userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockUserService)(nil).SetStatus), ctx, userID, isActive)
}

// MockBillingService is a mock of BillingService interface.
type MockBillingService struct {
	ctrl     *gomock.Controller
	recorder *MockBillingServiceMockRecorder
	isgomock struct{}
}

// MockBillingServiceMockRecorder is the mock recorder for MockBillingService.
type MockBillingServiceMockRecorder struct {
	mock *MockBillingService
}

// NewMockBillingService creates a new mock instance.
func NewMockBillingService(ctrl *gomock.Controller) *MockBillingService {
	mock := &MockBillingService{ctrl: ctrl}
	mock.recorder = &MockBillingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingService) EXPECT() *MockBillingServiceMockRecorder {
	return m.recorder
}

// GetAllPlans mocks base method.
func (m *MockBillingService) GetAllPlans(ctx context.Context) ([]*domain.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPlans", ctx)
	ret0, _ := ret[0].([]*domain.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPlans indicates an expected call of GetAllPlans.
func (mr *MockBillingServiceMockRecorder) GetAllPlans(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPlans", reflect.TypeOf((*MockBillingService)(nil).GetAllPlans), ctx)
}

// MockFeedbackService is a mock of FeedbackService interface.
type MockFeedbackService struct {
	ctrl     *gomock.Controller
	recorder *MockFeedbackServiceMockRecorder
	isgomock struct{}
}

// MockFeedbackServiceMockRecorder is the mock recorder for MockFeedbackService.
type MockFeedbackServiceMockRecorder struct {
	mock *MockFeedbackService
}

// NewMockFeedbackService creates a new mock instance.
func NewMockFeedbackService(ctrl *gomock.Controller) *MockFeedbackService {
	mock := &MockFeedbackService{ctrl: ctrl}
	mock.recorder = &MockFeedbackServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedbackService) EXPECT() *MockFeedbackServiceMockRecorder {
	return m.recorder
}

// SendFeedback mocks base method.
func (m *MockFeedbackService) SendFeedback(ctx context.Context, cmd domain.SendFeedbackCmd) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFeedback", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendFeedback indicates an expected call of SendFeedback.
func (mr *MockFeedbackServiceMockRecorder) SendFeedback(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFeedback", reflect.TypeOf((*MockFeedbackService)(nil).SendFeedback), ctx, cmd)
}
